In [79]:
import pandas as pd 
import numpy as np

In [80]:
bk = pd.read_parquet("airplane_data/bookings_2021.parquet", engine="fastparquet")
ckn = pd.read_parquet("airplane_data/checkins_2021.parquet", engine="fastparquet")
cl = pd.read_parquet("airplane_data/clients_2021.parquet")

In [81]:
bk2 = bk[['booking_id', 'planning_id', 'num_adults', 'num_children', 'num_infants']].copy()
ckn2 = ckn[['booking_id', 'planning_id', 'customer_id']].copy()

In [82]:
bk2['total_pass'] = bk2['num_adults'] + bk2['num_children']
grp = bk2.groupby('planning_id')['total_pass'].sum().reset_index(name='total_passengers')
grp.head()

   planning_id  total_passengers
0  PLN20210016                75
1  PLN20210017                75
2  PLN20210018                75
3  PLN20210019                75
4  PLN20210020                75

In [83]:
grp2 = ckn2.groupby('planning_id').size().reset_index(name='total_checkin_passengers')
grp = grp.merge(grp2, on='planning_id', how='left')
grp.sort_values(by='total_checkin_passengers').head()

      planning_id  total_passengers  total_checkin_passengers
5907  PLN20215923                75                        16
711   PLN20210727                75                        19
6571  PLN20216587                75                        22
3157  PLN20213173                75                        22
3601  PLN20213617                75                        22

In [84]:
bk_copy = bk[['booking_id', 'customer_id', 'planning_id', 'num_adults', 'num_children', 'num_infants', 'booking_status', 'price_per_ticket', 'booking_date']].copy()
cl_copy = cl[['client_id', 'date_of_registration']]

bk_cl = bk_copy.merge(cl_copy, left_on='customer_id', right_on='client_id', how='left')
bk_cl = bk_cl.drop(columns='client_id')
bk_cl.head()

,booking_id,customer_id,planning_id,num_adults,num_children,num_infants,booking_status,price_per_ticket,booking_date,date_of_registration
0,BK2021000001,CL20216134,PLN20210016,2,0,0,confirmed,1787.98,2021-01-02 03:37:25.181675,2021-01-01
1,BK2021000002,CL202132668,PLN20210016,1,0,0,rescheduled,1582.00,2021-01-02 02:35:11.947195,2021-01-01
2,BK2021000003,CL202130112,PLN20210016,1,0,0,confirmed,1725.31,2021-01-02 01:39:52.850387,2021-01-01
3,BK2021000004,CL202122654,PLN20210016,1,0,0,confirmed,1024.53,2021-01-02 02:25:28.106466,2021-01-01
4,BK2021000005,CL202126357,PLN20210016,1,0,0,confirmed,1488.67,2021-01-02 03:33:40.220035,2021-01-01

In [85]:
mask = bk_cl[bk_cl['date_of_registration'] > bk_cl['booking_date']]
mask

Empty DataFrame
Columns: [booking_id, customer_id, planning_id, num_adults, num_children, num_infants, booking_status, price_per_ticket, booking_date, date_of_registration]
Index: []